### ISSUE TITLE
Where to Upload LyCORIS (LoCon/LoHA)

### ISSUE THREAD

**Issue by shanmugad** [arenasys/qDiffusion#11]
Hi, 

There is a folder where i can upload Lora but i cannot find a folder to Upload LyCORIS (LoCon/LoHA)?. Should i upload this in Lora folder?, will it work? 

![image](https://github.com/arenasys/qDiffusion/assets/121617479/70ff10c1-af4f-4731-9ca4-62388de5158e)

**Comment by arenasys** [comment]
LoCon is supported and uses the same folder as LoRa (they are basically the same thing). LoHA and the other random LoRa variants are not supported.

**Comment by shanmugad** [comment]
> LoHA and the other random LoRa variants are not supported.

So, LoHA is not supported? I want to use this https://civitai.com/models/44164/millie-bobby-brown?modelVersionId=48809
