### ISSUE TITLE
Client crashes when attempting to draw mask

### ISSUE THREAD

**Issue by RyanTheInkling** [arenasys/qDiffusion#12]
Whenever I create a mask, and try to edit it by clicking on it twice, the GUI crashes. For a split second, I do see the first image in the img2img window, as if it was ready to be inpainted, but it crashes before I can do anything. The error that it keeps spitting out into crash.log is as follows:

GUI 2023-06-22 11:26:44.956255
Traceback (most recent call last):
  File "C:\Users\ryanh\Downloads\qDiffusion-master\source\canvas\renderer.py", line 201, in render
    gl.glGetError()
  File "C:\Users\ryanh\Downloads\qDiffusion-master\venv\lib\site-packages\OpenGL\platform\baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "C:\Users\ryanh\Downloads\qDiffusion-master\venv\lib\site-packages\OpenGL\error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glGetError,
	cArguments = (),
	result = 1282
)

How do I fix this? My computer is a 2011 HP ProBook 6560b, with an Intel Core i5-2420m, and a crappy Intel HD Graphics 3000.

**Comment by arenasys** [comment]
May be due to HD 3000 graphics losing OpenGL support on Windows 10: https://gist.github.com/rb-dahlb/26f316c5b6089807a139fc44ee69f0d1

I cant replicate the issue on my hardware, so have no way to fix it.

**Comment by RyanTheInkling** [comment]
For some reason, the OpenGL extensions viewer says that the card supports up to OpenGL 3.1, but why is qDiffusion only showing "2 2 0 0"? I did follow the steps in the link you provided, and the issue is still there.
![image](https://github.com/arenasys/qDiffusion/assets/41594800/75a6481b-240e-4130-af1c-f7f7b875de73)
![image](https://github.com/arenasys/qDiffusion/assets/41594800/a1f24e90-8013-482b-a05d-3a16215c40f7)
