### ISSUE TITLE
Generating multiple images error 

### ISSUE THREAD

**Issue by littletigerwolf** [arenasys/qDiffusion#14]
After last update, if set Batch size more than 1, program crashes with that log

GUI 2023-06-25 18:10:20.100167
Traceback (most recent call last):
  File "F:\qDiffusion-master\source\tabs\basic\basic.py", line 348, in result
    metadata = metadata[i] if metadata else None
KeyError: 1

**Comment by arenasys** [comment]
fixed by 87e9b39f2dbc5dbd50a4de282c4b2aef6ec67007
