### ISSUE TITLE
How to use ControlNet

### ISSUE THREAD

**Issue by shanmugad** [arenasys/qDiffusion#15]
I am unable to understand, How to use ControlNet as there is an no option. 

**1. Uploaded ControlNet in Correct folder** 

![image](https://github.com/arenasys/qDiffusion/assets/121617479/50bf3efb-81b1-4a7f-9c43-d5fd5048e60a)

**2. No Option to check ControlNet** 

![image](https://github.com/arenasys/qDiffusion/assets/121617479/91856d2f-1612-4db3-ab0d-744d7381fe60)

**3. No Option to choose Installed ControlNet** 

![image](https://github.com/arenasys/qDiffusion/assets/121617479/3f0c23d6-48d7-4219-bd94-723000643176)

_**I want something like with my custom image. Wear sunglasses, change hair colour to red, remove hand tatoo, etc**_ without changing face or unmasked area

**Comment by arenasys** [comment]
some ControlNet models are not supported yet

**Comment by shanmugad** [comment]
I want something like with my custom image. Wear sunglasses, change hair colour to red, remove hand tatoo, etc without changing face or unmasked area.

What kind of ControlNet should i download?
