### ISSUE TITLE
Is v-pred a thing?

### ISSUE THREAD

**Issue by Kilgorio** [arenasys/qDiffusion#16]
I am using the v-pred version of the furryrock model and this is all I get
![00000118-06270317](https://github.com/arenasys/qDiffusion/assets/77736418/cfc47dd3-750a-408b-8f65-59b115c264c7)

**Comment by Kilgorio** [comment]
this model: https://huggingface.co/lodestones/furryrock-model-safetensors/blob/main/fluffyrock-1088-megares-terminal-snr-vpred/fluffyrock-576-704-832-960-1088-lion-low-lr-e59-terminal-snr-e32.safetensors

**Comment by arenasys** [comment]
need the models `.yaml` config file so qDiffusion knows its v prediction and not epsilon prediction

**Comment by Kilgorio** [comment]
Thanks! Also I wanna ask is there a way to use tag autocomplete? If there isn't are you planning to add it?

**Comment by arenasys** [comment]
In the models tab, right click any wildcard and toggle the vocab option. If the wildcard is a csv file: the first column is the tag and the last column is extra info thats shown with the tag in the autocomplete ui.

**Comment by Kilgorio** [comment]
Thanks again. Is csgg rescale a thing?

**Comment by arenasys** [comment]
it is now, need to show Advanced Parameters then it will be under Misc

**Comment by Kilgorio** [comment]
Thank you very much.
