### ISSUE TITLE
Bug - Client Application automatically close

### ISSUE THREAD

**Issue by shanmugad** [arenasys/qDiffusion#17]
Hi, 

it was working fine yesterday, after recent update when i open Client it automatically getting closed. 

Error Video : https://youtu.be/raRMwou0MeQ

**Comment by Lrive** [comment]
[crash.log](https://github.com/arenasys/qDiffusion/files/11885483/crash.log)
here is my crash log

**Comment by arenasys** [comment]
delete the folder `editor` folder in `source/tabs`.

**Comment by arenasys** [comment]
Fixed by 4c393c6a41c809be283335156ecead6022640633. But if you are affected by the crash already you will need to delete the `editor` folder, or manually update (`git pull`).

**Comment by shanmugad** [comment]
After deleting Editor folder, it working fine

**Comment by Lrive** [comment]
also fixed 👍
