### ISSUE TITLE
bug: Inpaint with mask and padding -> freeze

### ISSUE THREAD

**Issue by Derfuu** [arenasys/qDiffusion#24]
When using inpainting with mask and padding (not full image) - GUI freezes, showing "Upscaling" and "Working..." in current state and after this - chashes or keeps working, but without any response to actinos. After closing GUI - python process still hanging with all memory it used.

Img size - 864x1152

Inpaint settings:
- Strength: 0.85
- Upscaler: UltraSHarp-4x
- Padding: 112
- Mask blur: 4
- Mask expand: 0
- Mask fill: Original

*GUI 2023-08-03 11:46:29.340816*
```py
Traceback (most recent call last):
  File "F:\NeuralNetworks\Apps\qDiffusion\source\parameters.py", line 744, in sync
    closest_match = self.gui.closestModel(value, available) or available[0]
IndexError: list index out of range
```

**Comment by arenasys** [comment]
598e45801ae9cf266982faf62bf5da665a994206 should fix that error, but it doesn't match what you described. That error would happen when importing an image while disconnected.

**Comment by Derfuu** [comment]
This Traceback is the only thing that was in the crash log after the freeze. Same actions did not write anything there further. Other tracebacks are far early, so idk certanly what cause this freezes.
I'd suggest that this happens only when you first time use inpaint with mask + drawing on an image with SDP attention.

**Comment by Derfuu** [comment]
Options:
- Image size: 864x1152 (or 384x512 with 2.25 upscale)
- 30 steps

Sampler:
- DPM++ 2M 
- Exponential
- ETA 1.0

Inpaiting:
- Strength 0.85
- Upscaler: 4x-UltraSharp
- Padding 80
- Max blur 4
- Mask expand 1
- Fill Original

Operation:
- Attention: SDP

What have i done:

- Take img from gallery
- copied all its data except seed
- draw on img
- set mask
- set padding 
- Click generate
- Wait...

After start generation it stops on Upscaling and don't show preview or progress on side bar. I can still switching tabs, write prompts, look gallery and refresh models, but when i try to cancel - it don't respond and continiously Working without any progression. If i try to reload server it freezes and after the GUI window closes - python process still works on it without qDiffusion process. Even if i close GUI manually (not throught Task manager) - python process still hanging with nearly full CPU usage (80-90%).

I'd suppose that this bug only appears with only vertical image (and maybie only with this size), because with 1152x864 it works well.

**Comment by arenasys** [comment]
I've made some tweaks to SR upscaling, could have fixed it.
