### ISSUE TITLE
Feature Request/Question: Regional Prompter?

### ISSUE THREAD

**Issue by Saniee** [arenasys/qDiffusion#25]
Hey, I have a question and a feature request if what I suspect is right now implemented.
Is Regional Prompter a feature already in this tool? If yes, where can I find it/enable it?
---
If its not a feature, could it be added? Its a very good extension for automatic111, and with my low end hardware its hard to get it without paying for google collab pro (or restarting each second prompt which takes minutes), which is rather expensive each month.

**Comment by arenasys** [comment]
It exists already as Subprompts. Your prompt should look like: `background prompt AND area 1 prompt AND area 2 prompt` etc. Then add the Subprompt input, open it and paint the areas.

**Comment by Saniee** [comment]
Oh! Great, thanks a lot for clarifying.
