### ISSUE TITLE
LoRa problem

### ISSUE THREAD

**Issue by 1WhiteDragon1** [arenasys/qDiffusion#30]
Seems like LoRas doesn't work at all. I'm getting default model's results. No one prompt isn't helping to solve this problem. Yesterday everything was fine. Any ideas what's going on and how to fix this?

**Comment by arenasys** [comment]
https://github.com/arenasys/sd-inference-server/commit/197ca9db1a0f688d8367170ca4d5b6f8f1b8b100 should fix it. update and restart qdiffusion, and remake your colab if you are using one.

**Comment by 1WhiteDragon1** [comment]
Oh, this is so easy.. Okay, i'll do it. Thank you!

Update: Everything works fine, problem solved!

**Comment by 1WhiteDragon1** [comment]
I've experienced problem with this model. Generates white picture with some noise.

https://civitai.com/models/92450?modelVersionId=124661

**Comment by littletigerwolf** [comment]
> I've experienced problem with this model. Generates white picture with some noise.
> 
> https://civitai.com/models/92450?modelVersionId=124661

Are you use Hires fix?

**Comment by 1WhiteDragon1** [comment]
Yes

**Comment by littletigerwolf** [comment]
> Yes, Hires Upscaler i use - RealESRGAN_x4plus_anime_6B

I slightly misread your question x) I thought you were just getting noise when generating...

I've read a few comments under the model and it seems the problem is not with qDiffusion, but with the model itself, or rather its settings. In turn, I recommend trying these models: [YiffyMix (i recommend 31)](https://civitai.com/models/3671/yiffymix)  or [BB95](https://civitai.com/models/17649)

**Comment by arenasys** [comment]
> I've experienced problem with this model. Generates white picture with some noise.
> 
> https://civitai.com/models/92450?modelVersionId=124661

Looks like the detection fails for this model so you need the yaml config file.
I did ask the model author if they can add some metadata to the checkpoint so programs know its v prediction without a config file. Will have to wait and see if that happens.

**Comment by 1WhiteDragon1** [comment]
> > I've experienced problem with this model. Generates white picture with some noise.
> > https://civitai.com/models/92450?modelVersionId=124661
> 
> Looks like the detection fails for this model so you need the yaml config file. I did ask the model author if they can add some metadata to the checkpoint so programs know its v prediction without a config file. Will have to wait and see if that happens.

Okay, looking forward for model's author reply, Thank you!

**Comment by 1WhiteDragon1** [comment]
> > Yes, Hires Upscaler i use - RealESRGAN_x4plus_anime_6B
> 
> I slightly misread your question x) I thought you were just getting noise when generating...
> 
> I've read a few comments under the model and it seems the problem is not with qDiffusion, but with the model itself, or rather its settings. In turn, I recommend trying these models: [YiffyMix (i recommend 31)](https://civitai.com/models/3671/yiffymix) or [BB95](https://civitai.com/models/17649)

The problem is.. I have some LoRas that work only with "FluffyRock" model(as LoRa's author said). But, i haven't try models you suggest yet. Maybe it will work..

**Comment by arenasys** [comment]
> > > I've experienced problem with this model. Generates white picture with some noise.
> > > https://civitai.com/models/92450?modelVersionId=124661
> > 
> > 
> > Looks like the detection fails for this model so you need the yaml config file. I did ask the model author if they can add some metadata to the checkpoint so programs know its v prediction without a config file. Will have to wait and see if that happens.
> 
> Okay, looking forward for model's author reply, Thank you!

For now I added a "Prediction" option under Misc (enable advanced parameters in settings first), set it to "V" when using v-prediction models like FluffyRock, then you dont need the config file.
