### ISSUE TITLE
Question: Tile Resample and Ultimate SD Upscale

### ISSUE THREAD

**Issue by littletigerwolf** [arenasys/qDiffusion#31]
Will you implement this in your GUI sometime in the future?
This is not a request for immediate implementation, this is a question about plans for this ControlNet+Script

**Comment by arenasys** [comment]
Yes, generating with tiles is planned, and the tile controlnet. There are alot of techniques out there related to tiled diffusion, so dont expect all of them.

**Comment by littletigerwolf** [comment]
> Yes, generating with tiles is planned, and the tile controlnet. There are alot of techniques out there related to tiled diffusion, so dont expect all of them.

Thank you for answer! A am closing Issue.
