### ISSUE TITLE
_ in the models path

### ISSUE THREAD

**Issue by littletigerwolf** [arenasys/qDiffusion#35]
**Describe the bug**
Having _ in the model path prevents the GUI from seeing the models.

**Screenshots**
<details>
<summary>Screens</summary>

![изображение](https://github.com/arenasys/qDiffusion/assets/16870344/deae413f-dc65-468a-93a7-9a1044c18d64)
![изображение](https://github.com/arenasys/qDiffusion/assets/16870344/fc9d403a-2d4f-43f5-88a1-b34191b32f8c)
</details>

**System:**
 - Mode: [Local]
 - OS: [Windows]
 - GPU: [Nvidia]

**Comment by arenasys** [comment]
fixed by https://github.com/arenasys/sd-inference-server/commit/91e8177fceab8e9cd961d509b0a6afbd5c13beaa.
files/folders starting with underscores are filtered intentionally, but it should only be for subfolders.
```
SHOWN:
E:\_AI\qDiffusion\models\SD\model_name.safetensors
E:\_AI\qDiffusion\models\SD\subfolder\model_name.safetensors

FILTERED:
E:\_AI\qDiffusion\models\SD\_model_name.safetensors
E:\_AI\qDiffusion\models\SD\_subfolder\model_name.safetensors
```
etc.
