### ISSUE TITLE
Difference in generation result in qDiffusion and Automatic

### ISSUE THREAD

**Issue by littletigerwolf** [arenasys/qDiffusion#36]
This is not a suggestion or a bug (unless you think otherwise), it's just curiosity because I haven't been able to figure out why this happens.

When generated using the same model, the same embendings, lora, all parameters (in fact, all), the generated images in your GUI and in Automatic are different.  Sometimes - as, for example, in the V-Pred models EasyFluff PreRelease v2 - they are dramatically different.

If you have the opportunity and time, could you explain what this might be related to?  This is pure curiosity, since it doesn’t really interfere with using your GUI, which in my eyes is much more convenient, I just want to know the answer to the question that’s stuck in my head.

**Comment by arenasys** [comment]
Mostly its due to floating point precision. Even if qDiffusion is calculating the same thing as Automatic, the result could vary slightly if the order of operations is different or precision is cast during the calculation (happens a lot in Automatic's code).

**Comment by littletigerwolf** [comment]
> Mostly its due to floating point precision. Even if qDiffusion is calculating the same thing as Automatic, the result could vary slightly if the order of operations is different or precision is cast during the calculation (happens a lot in Automatic's code).

Hm, i have an idea, and i check it this evening.
Tell me, how is random noise generated in the GUI?  In Automatic there are three settings, GPU, CPU, NV, and it seems that in CPU mode the results are exactly similar to what is obtained in qDiffusion.  I need to check this...

**Comment by arenasys** [comment]
its GPU noise, compatible with A1111 (or it was months ago when i wrote it)

**Comment by littletigerwolf** [comment]
I checked what I said above and, no, it does not affect...

When talking about the difference in generation results, I do not mean a small difference, but rather an extremely significant one - as if different models or different samplers are used. Below is an example.
That's why I wrote to you, in the hope that maybe you can reveal the reason for this.


<details>
<summary>Generated arts</summary>
![00001-683535432](https://github.com/arenasys/qDiffusion/assets/16870344/0c70751e-e64a-47f0-a09f-d47945d9ac3d)
![00000221-10192206](https://github.com/arenasys/qDiffusion/assets/16870344/bb484534-ccbb-4574-807e-a55d3ba37523)
</details>

**Comment by arenasys** [comment]
You are using prompt emphasis incorrectly for one. `word:1.4` wont work `(word:1.4)` will work, `(word:1.4 something)` wont work, `(word something:1.4)` will work

**Comment by littletigerwolf** [comment]
Thank you for answering and spending your time on this.

I change prompts (thanks for the explanation!), but the difference is still extremely significant. Not even in the details, but specifically in the rendering of the finished image - as you can see, the A1111 on the same model better reproduces the style of the original (twokinds).
I have very little understanding of exactly how a neural network works, and how the prompt is converted into tokens for the model (I hope I'm not talking nonsense), but could the different way of doing this conversion be a problem, or are you using exactly the same method as and in A1111?

<details>
<summary>Generated arts</summary>
![image](https://github.com/arenasys/qDiffusion/assets/16870344/be24d7cb-e152-4f87-8b29-400676848190)
![image](https://github.com/arenasys/qDiffusion/assets/16870344/4d761f86-757d-4ee0-b7b3-b98a90cdf58d)
</details>

**Comment by arenasys** [comment]
CLIP encoding is identical if using the same (valid) syntax and parameters. If you want to track down the source of the difference, I would start with a simple setup where qDiff and A1111 match closely then add in more stuff and see where it diverges.

**Comment by littletigerwolf** [comment]
I formed an XY Grid and got very... Unusual results
Upper - qDiffusion, lower A1111
It seems to me that there shouldn’t be such a dramatic difference when using different samplers, or am I misunderstanding something?


<details>
<summary>Generated arts</summary>

![image](https://github.com/arenasys/qDiffusion/assets/16870344/3821ff61-e791-424a-a4de-04d9a4ba6399)

![image](https://github.com/arenasys/qDiffusion/assets/16870344/1afdedc3-6358-4259-a35b-42680b4cb893)
</details>

**Comment by littletigerwolf** [comment]
> CLIP encoding is identical if using the same (valid) syntax and parameters. If you want to track down the source of the difference, I would start with a simple setup where qDiff and A1111 match closely then add in more stuff and see where it diverges.

I tried every possible setting, but honestly I didn't find anything that made that much of an impact because all the basic settings remained the same.
I'm still tinkering with the A1111 settings, maybe I'll be able to find the reason for such a big difference...

**Comment by arenasys** [comment]
Check without the embeddings (you have boring_e621_fluffyrock_v3, boring_e621_v4, deformityv6), check your CLIP skip is the set same, check with a non-vpred model, etc.

**Comment by littletigerwolf** [comment]
*very confused and incomprehensible sounds*

I remove embendings, a-a-and...

But... Why? I use same embendings! I really just copy file from qDiff to A1111 o_0

<details>
<summary>Generated arts</summary>
![image](https://github.com/arenasys/qDiffusion/assets/16870344/8bdcbdbb-d977-41fb-8e5a-d7227eca456c)
![image](https://github.com/arenasys/qDiffusion/assets/16870344/b71c3a28-cf85-4cb3-af93-fb18cfa91644)
</details>

**Comment by arenasys** [comment]
Can you narrow which embedding isnt working the same as A1111, just add them one at a time and see where it diverges

**Comment by littletigerwolf** [comment]
boring_e621_fluffyrock_v3
boring_e621_v4

Any of these embeddings radically changes the generation result

<details>
<summary>Embeddings </summary>

[negative.zip](https://github.com/arenasys/qDiffusion/files/13056721/negative.zip)


</details>

**Comment by arenasys** [comment]
Ill fix them, just other stuff on the list first. Open issues are left open because I plan on addressing them.

**Comment by arenasys** [comment]
qDiffusion's embedding code seems to be working fine. The fact the A1111 gens you posted look very similar with and without the embeddings makes me think its an A1111 issue.
