### ISSUE TITLE
Can't connect to remote qDiffusion

### ISSUE THREAD

**Issue by 1WhiteDragon1** [arenasys/qDiffusion#38]
I connect according to guide but i see error:
"Error while Connecting.
server rejected WebSocket connection: HTTP 530"

What should i do to fix this problem? 

P.S Didn't use qDiffusion for a month, maybe i need to reinstall programm?

Upd: Yes, reinstall fixed the problem.

**Comment by Mlaofmd** [comment]
this cloudflare problems, and now its fixed
