### ISSUE TITLE
Stuck Encoding

### ISSUE THREAD

**Issue by Kilgorio** [arenasys/qDiffusion#4]
I am using arch and an amd gpu and it seems to be stuck encoding
![image](https://github.com/arenasys/qDiffusion/assets/77736418/f0b488a0-e28c-41ce-b0b7-150e4ffc322c)

**Comment by arenasys** [comment]
AMD's ROCm doesnt like consumer GPU's, so you need to override what architecture it thinks your GPU is, for RDNA (RX 5000-7000) thats: `export HSA_OVERRIDE_GFX_VERSION=10.3.0`

**Comment by arenasys** [comment]
launcher will now set the environmental variables for you if you have none set: 2dd5af913fc665c6d59470d98820b2fc15b83348
