### ISSUE TITLE
Clear my Local Disk after closing program

### ISSUE THREAD

**Issue by r3ngali** [arenasys/qDiffusion#40]
I want clear my Local Disk (C:) after running locally qDiffusion (installed on other local disk (F:)). I noticed that after closing the program, the memory on the disk becomes 1.7-2.5 GB less. Where qDiffusion saved files?

**Comment by arenasys** [comment]
qDiffusion doesn't save files anywhere except for the folder its in. The missing space could be python caching qDiffusion's dependencies or something unrelated.
