### ISSUE TITLE
endpoint not generating normaly (COLLAB)

### ISSUE THREAD

**Issue by Mlaofmd** [arenasys/qDiffusion#41]
**Describe the bug**
I have issue with remote, when I starting this code, but then I getting password, endpoint just generates: wss://api.trycloudflare.com, anyone can fix it?

**Traceback**
Error while Connecting.
server rejected WebSocket connection: HTTP 400

**Screenshots**
![image](https://github.com/arenasys/qDiffusion/assets/52864321/6641f8b9-74b2-4b70-a314-efd077808bc7)

![image](https://github.com/arenasys/qDiffusion/assets/52864321/fc3fc819-34d1-44da-96c4-0e7f99e65d7d)

**System:**
 - Mode: Remote
 - OS: Windows
 - GPU: T4

**Comment by arenasys** [comment]
https://www.cloudflarestatus.com/
Cloudflare is having troubles. You can try the Kaggle notebook if you want

**Comment by Mlaofmd** [comment]
Oh okay, thanks.
