### ISSUE TITLE
Subpromts guide

### ISSUE THREAD

**Issue by littletigerwolf** [arenasys/qDiffusion#44]
May I ask you to write a precise guide for using Subpromts if possible? The fact is that when you try to use them (background promt AND area 1 prompt AND area 2 prompt) during generation, the result is very unpredictable.
Tell me, what am I doing wrong?
<details>
<summary>example</summary>

![изображение](https://github.com/arenasys/qDiffusion/assets/16870344/c4856d8f-dd66-4b31-b317-1daef88a4e92)

![00000214-11051528](https://github.com/arenasys/qDiffusion/assets/16870344/a1173f39-8b8a-40a7-84f1-a055d627bbbe)
![00000215-11051529](https://github.com/arenasys/qDiffusion/assets/16870344/da320f92-39ab-4cf0-89c3-c1d4cae86264)
![00000216-11051529](https://github.com/arenasys/qDiffusion/assets/16870344/91573279-61f5-44c2-8b7b-05c4d56f2d65)

</details>

**Comment by arenasys** [comment]
You are using them fine, its just Subprompts being finicky. In the red area its fighting between generating a forest and generating a fox and having a hard time, you can also see it doesn't quite know what scale to draw them in and is trying to "escape" the area (the huge partial fox tail in the bottom image, etc).

Can try alter the weights, by default the weighting is `detailed forest background :1.0 AND red fox :0.8 AND white dragon :0.8`, messing with the weights too much can fry the image though.
Can try add something into the background prompt so it doesn't conflict so much `detailed forest background [with animals]`. 
Can also try crudely sketch the scene with the Image input so it has something to go off (blobs of colors are usually enough of a clue).

**Comment by littletigerwolf** [comment]
Thank you! I try this.
