### ISSUE TITLE
Error while Sending

### ISSUE THREAD

**Issue by 1WhiteDragon1** [arenasys/qDiffusion#47]
I've got an error while generating. Description of error:

Error while Sending
Unable to serialize: key 'preview_interval' value: <PyQt5.QtCore.QVariant object at 0x000002B1B203FED0> type: <class 'PyQt5.QtCore.QVariant'>

**Comment by arenasys** [comment]
should be fixed by 72792804020436a7a8d3d681eb2b516407c92a1c. please update.

**Comment by 1WhiteDragon1** [comment]
It's now working, thanks!
