### ISSUE TITLE
Synchronous workloads for 2 different devices

### ISSUE THREAD

**Issue by stromtroopertk421** [arenasys/qDiffusion#49]
Hi, i have asetup with 2 GPUs, how ever even if I select another device the clients wait until the first request is completed. Is it possible to use 2 devices at the same time for 2 different generations on 2 GPUs on the same server?

**Comment by arenasys** [comment]
Currently a single server can only serve 1 request at a time, so for simultaneous workloads you would need multiple servers running on the same machine, one for each GPU (possibly also using `CUDA_VISIBLE_DEVICES` etc).

**Comment by stromtroopertk421** [comment]
Thanks you, I hope we can have this with singles stanced in the future!
