### ISSUE TITLE
Some recomendations

### ISSUE THREAD

**Issue by littletigerwolf** [arenasys/qDiffusion#5]
Highres - we need a more understandable application interface, or at least a tutorial. So, at the moment, you have to apply a mask and regenerate, and not just do Upscale

HR fix - judging by the Readme, it is present, but there is no setting in the interface

For reasons that are not entirely clear, for the same generation parameters, when using the same seed, the results are different. Constantly - when generating several images at once in one batch

I hope I'm not pointing out any obvious or stupid things, and thank you for your hard work - other than the above, everything else works great

p.s. Being able to erase a badly drawn mask with RMB is brilliant

**Comment by arenasys** [comment]
Highres is HR Fix, HR Fix only applies when doing txt2img (so, no image in your inputs).

When generating several images in a batch the seed will be incremented. Ex, for batch size 4, seed 1234, the batch's seeds will be: 1234, 1235, 1236, 1237

**Comment by littletigerwolf** [comment]
Thank you for answer!
About seed increment, i know about it, i mean first image in batch. But i checked it, and could not reproduce, now i think it was my mistake.

So, if Highres is HR fix, how i can upscale generated images? Or it's not implemented now?

**Comment by arenasys** [comment]
Having `HR Factor` set higher than 1.0 will upscale the image after txt2img and then do an additional img2img pass on it (which is called HR Fix). If you want to upscale an existing image, put it into the inputs, set the resolution to the final resolution you want, set `Strength` low (under Inpainting) and generate
