### ISSUE TITLE
Tile ControlNet workflow?

### ISSUE THREAD

**Issue by littletigerwolf** [arenasys/qDiffusion#50]
This ControlNet, as far as I know, allows you to Upscale images in tiles, which allows you to bypass the memory limitation when Upscaled to high - 2-4k - resolutions. However, in qDiffusion, when used, it immediately tries to Upscale, which causes torch.cuda.OutOfMemoryError.

And, in fact, my question is, is this a feature of ControlNet, implemented without using the analogue of SD Upscale/Ultimate SD Upscale from A1111, or is it still a bug?

**Comment by arenasys** [comment]
Probably using an SR model to upscale? Use Lanczos or similar.

**Comment by littletigerwolf** [comment]
Yes, it's working. It is possible to implement SR model to use with Tile ControlNet?

And, somequestions about settings:

What does Tile scale? What is it for?
Strength - it is a Sampling Down Rate, or something else?

**Comment by arenasys** [comment]
Tile ControlNet functions as an Upscaler, using an SR model before it makes little sense.

The whole process is to upscale the image to your target resolution, then split it into tiles, each tile is then upscaled to the `Tile size` and img2img'd using the Tile Controlnet, then the finished tiles are downscaled and assembled together into an image. Can think of it as a bunch of inpainting operations that are using `Padding`.

So note there are two upscaling operations, the first is the regular img2img upscale to get the image to match your target resolution (the one you OOM'd on), the second is the individual Tile upscale which is controlled by `Tile scale`. The latter upscale is to increase the amount of detail in each tile (like inpainting at a higher resolution).

In the top right under the resolution is another number which is the Tile size "pre Tile upscale" but "post Img2Img upscale", so if it says 300 then tiles of size 300 are cut out of the image, then upscaled to 512 then img2img'd, downscaled back to 300 then assembled into the output. I may change it to be "pre Img2Img upscale", in that case it would show the tile size on the original image before any upscaling.

`Strength` is the ControlNet strength like with all the ControlNets. If you want to perform the Tiling procedure without the ControlNet then set the `Strength` to 0 and it will not be loaded.

**Comment by littletigerwolf** [comment]
Thanks for the clarification, everything has become much clearer now.  One last question before I close Issue: did I understand correctly that the Down Sampling Rate setting is not currently implemented in qDiffusion?

**Comment by arenasys** [comment]
Not sure what that setting is, im not familiar with the other implementations of Tile Controlnet.
