### ISSUE TITLE
Why inpainting unavailable?

### ISSUE THREAD

**Issue by Mlaofmd** [arenasys/qDiffusion#52]
**Describe the bug**
After updating qDiffusion inpainting its unavailable, Im tried to reinstall but its not works, please help

**Screenshots**
![image](https://github.com/arenasys/qDiffusion/assets/52864321/f75ed22f-ff2d-44ca-b552-12e7189f4989)

**System:**
 - Mode: Remote
 - OS: Windows
 - GPU: T4

**Comment by arenasys** [comment]
https://github.com/arenasys/qDiffusion/wiki/Guide#inpainting
