### ISSUE TITLE
Will SDXL models ever work?

### ISSUE THREAD

**Issue by ItsNoted** [arenasys/qDiffusion#55]
I tried using this on Windows 10. I've been using Fooocus  with XL models without issues cranking images out at 1920x1080 using 30 steps getting amazing images in about 35 seconds. I tried using this and first, it takes ages to finish a 512x512 image, then when its done the image is black. And that's after waiting 4-5 minutes. I tried using different settings and cannot for the life of me figure out what the issue is.

GPU: 2080ti 11gb
CPU: i9
RAM: 128GB

**Comment by ItsNoted** [comment]
I think It's because I was trying to use SDXL models. I tried a 1.5 model and it seems to work better.

**Comment by arenasys** [comment]
https://github.com/arenasys/qDiffusion/wiki/Guide#troubleshooting

**Comment by ItsNoted** [comment]
Path of least resistance. Nice.

**Comment by arenasys** [comment]
FP32 VAE precision should let SDXL generate, close this is it works
