### ISSUE TITLE
Random crashes* on linux device

### ISSUE THREAD

**Issue by MeFinity** [arenasys/qDiffusion#58]
**Describe the bug**
GUI goes unresponsive randomly on Generate

**Traceback**
All i got is a terminal output
```
event went missing during delivery! (nested sendEvent() is not allowed)
```

**Screenshots**
![ssobfuscated](https://github.com/arenasys/qDiffusion/assets/72972952/0c58940f-01f9-4d0d-a835-76c2c1f6b91b)
**System:**
 - Mode: Remote
 - OS: Arch Linux, GNOME DE, Tried X11 and Wayland
 - GPU: Its remote

**Comment by arenasys** [comment]
I actually develop qDiffusion on Arch with GNOME, so I dont think its specific to that. Seems to be freezing on the Fetch, could be locking up trying to write the image?

**Comment by MeFinity** [comment]
Yep, the preview loads fine but the full image makes the program unresponsive, seeing the remote server; the image generated fine, and the browser frontend also loads it fine without anything bugging out

**Comment by arenasys** [comment]
I added two debug modes under settings, after setting them make sure you restart qDiffusion. See if the crash persists with either set ("Disable Saving" or "Disable Gallery")

**Comment by arenasys** [comment]
c7c5a7653966b7ca6b04617c01ac77819366c16b possibly helped with this

**Comment by MeFinity** [comment]
so far, no unresponsiveness! generated a few images in 1024x1024 and i get zero crashes*
thanks for fixing the issue, i will let you know if it returns
