### ISSUE TITLE
Pose ControlNet workflow

### ISSUE THREAD

**Issue by littletigerwolf** [arenasys/qDiffusion#65]
I need help with Pose ControlNet in qDiffusion, because i always get a blank black image from any image or photo. Even when I found the actual screenshot of the controlNet generated pose, I still got a black image.

**Comment by arenasys** [comment]
+ -> Control -> Pose. Drag in the image. Press the little refresh button to annotate it.

**Comment by littletigerwolf** [comment]
Thanks, i just found, that some image cannot be annotated

**Comment by arenasys** [comment]
Can annotate them manually now, since ive added a pose editor

**Comment by littletigerwolf** [comment]
> Can annotate them manually now, since ive added a pose editor

Yes, i see yesterday, it's a great function!
