### ISSUE TITLE
Wrong Architecture - Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by mclmt-owo** [arenasys/qDiffusion#69]
**Describe the bug**

Running `bash /home/collin/Downloads/qDiffusion-master/source/start.sh` downloads python3.10.12 and what I'm guessing is the wrong version of pip. I can't get a version number for the version of pip downloaded, as it simply throws a `Illegal instruction (core dumped)` error. If I had to hazard a guess, I'd say the version of pip bundled with "indygreg/python-build-standalone" is for the wrong architecture. 

**Traceback**

```
collin@hazardous-hyena:~/Downloads/qDiffusion-master$ python/bin/python3 --version
Python 3.10.12
collin@hazardous-hyena:~/Downloads/qDiffusion-master$ python/bin/pip3 --version
Illegal instruction (core dumped)
collin@hazardous-hyena:~/Downloads/qDiffusion-master$ bash ./source/start.sh
./source/start.sh: line 32: 406624 Illegal instruction     (core dumped) ./python/bin/python3 source/launch.py "$@"
```

**Screenshots**

N/A

**System:**
 - Mode: Neither
 - OS: Linux x86_64
 - GPU: Nvidia GTX 1660 Super

**Comment by arenasys** [comment]
Its built for CPUs from the last decade (post Haswell/Excavator). If thats the issue replace the `x86_64_v3` in the url with `x86_64_v2`. See [here](https://gregoryszorc.com/docs/python-build-standalone/20240224/running.html)

**Comment by mclmt-owo** [comment]
That fixed the issue. My Intel Xeon E5-2670 is Sandy Bridge, which is just 2 years too early to the party :)

Thanks for the heads up. `v2` fixed it.
