### ISSUE TITLE
Suggestion: Support for Automatic1111

### ISSUE THREAD

**Issue by Revaz-Goguadze** [arenasys/qDiffusion#70]
is it possible to make extension for Automatic1111 to accept sd server inference? i found similar service by omniinfer (https://github.com/omniinfer/sd-webui-cloud-inference )but its only Suitable for their paid service

**Comment by arenasys** [comment]
Not possible, they are completely different codebases.

**Comment by arenasys** [comment]
Oh wait, you are asking if an extension could be made for Automatic1111? Im sure it can be done, im not writing it though. Also probably want to ask in the Automatic1111 repo, not here.
