### ISSUE TITLE
Can't select downloaded detailer in gui

### ISSUE THREAD

**Issue by Revaz-Goguadze** [arenasys/qDiffusion#72]
![image](https://github.com/arenasys/qDiffusion/assets/128724330/79ae59f8-75b6-42cb-96ac-a4e4fbbecfd2)
![image](https://github.com/arenasys/qDiffusion/assets/128724330/701e389a-b8ce-4584-a3b3-ac8185b72a0a)
does it need another name on folder?

**Comment by arenasys** [comment]
Its expecting `.pt` detailer models. I pushed a change to allow `.safetensors` models, could still be incompatible somehow though.

**Comment by Revaz-Goguadze** [comment]
> Its expecting `.pt` detailer models. I pushed a change to allow `.safetensors` models, could still be incompatible somehow though.

thx now it works
