### ISSUE TITLE
LoRa for XL models

### ISSUE THREAD

**Issue by Vol4ikk** [arenasys/qDiffusion#73]
Hello
Is LoRa support planned for XL models?
Apparently, only the basic model is working now
Thanks for your GUI, the best

**Comment by arenasys** [comment]
Its already supported.

**Comment by NamelessButler** [comment]
Lora do not work on negative prompt, `negative` loras are intended to be used like
`<lora:AAA:-1>` in prompt.

**Comment by Vol4ikk** [comment]
> Loras/Lycoris do not work in `Negative Prompt`. If you want to use them use with negative str in `Prompt`. ie:
> 
> ```
> <lora:AAA:-1>
> ```

Just in case, I checked, -1 does not work in XL LoRa
I also checked in automatic1111, it works and you can even use several LoRas in the negative part using :1
