### ISSUE TITLE
No links generated on Sagemaker

### ISSUE THREAD

**Issue by eyetest42** [arenasys/qDiffusion#76]
Attempting to use the web version. Gets as far as generating a password, but stops before links appear. Updating the notebook doesn't have any effect.
Using Firefox on a Mac.

**Comment by arenasys** [comment]
sagemaker notebook updated. should work if you just add this disable line to the first cell, above the enable line:
```
!./zrok disable
!./zrok enable "$ZROK_TOKEN"
```

**Comment by eyetest42** [comment]
> [ERROR] no environment found; nothing to disable!
> ]10;?\[   0.383]   ERROR main.(*enableCommand).run: the zrok service returned an error: [POST /enable][401] enableUnauthorized 
> there was a problem enabling your environment!
> 
> you are trying to use the zrok service at: https://api.zrok.io/
> 
> you can change your zrok service endpoint using this command:
> 
> $ zrok config set apiEndpoint <newEndpoint>
> 
> (where newEndpoint is something like: https://some.zrok.io/)
> 
> PASSWORD: puIhEXtz
> The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
> 0it [00:00, ?it/s]
> SERVER: starting
> FAILED TO CREATE TUNNEL, LOG:
> [ERROR] unable to load environment; did you 'zrok enable'?

**Comment by arenasys** [comment]
says theres a problem enabling the zrok environment, i would get a new token

**Comment by eyetest42** [comment]
so the default token is no good anymore? that sucks
unfortunately that means figuring out what zrok even is and how tf it works...

**Comment by eyetest42** [comment]
new token is working so far
