### ISSUE TITLE
"ModuleNotFoundError: No module named 'bson'"

### ISSUE THREAD

**Issue by jear3073** [arenasys/qDiffusion#79]
**Describe the bug**
All I did was open the app after first startup (meaning after python and the other stuff was done) and choose "remote" and installed it
and then it got to "pygit2" it stopped and said the traceback message

is it simple fix?

**Traceback**
GUI 2024-07-26 01:55:41.662334
Traceback (most recent call last):
  File "D:\qDiffusion-master\source\main.py", line 431, in doneInstalling
    self.done()
  File "D:\qDiffusion-master\source\main.py", line 385, in done
    start(self.engine, self.app)
  File "D:\qDiffusion-master\source\main.py", line 503, in start
    import gui
  File "D:\qDiffusion-master\source\gui.py", line 5, in <module>
    import bson
ModuleNotFoundError: No module named 'bson'

**Screenshots**
![Screenshot (30-1)](https://github.com/user-attachments/assets/b97f58e1-dd78-48de-a5ac-e88cbbf3cef2)

 - Mode: Remote
 - OS: Windows

**Comment by arenasys** [comment]
Seems it failed to install the dependencies for some reason. What happens when you run it again?

**Comment by jear3073** [comment]
Then when I do that it gives me the "not owner of file" error and locks me out
I go thru the steps to give myself access again and it still Everytime locks me out with no access 

I've uninstalled and reinstalled it several times, this is what happened every time

**Comment by arenasys** [comment]
Seems like some kind of permission issue with your `D:\` drive, not a qDiffusion issue. Some Ideas: Make sure you are not running qDiffusion as admin. Can try make a folder at the base of `D:\` drive and install qDiffusion in that (like `D:\blahblah\qDiffusion-master`). Use the built-in windows tool for extracting the zip (other tools may create the files with weird permissions).
