### ISSUE TITLE
Program settings confusion (Colab)

### ISSUE THREAD

**Issue by shanmugad** [arenasys/qDiffusion#8]
![image](https://github.com/arenasys/qDiffusion/assets/121617479/26850baf-753f-4141-8493-6193b1a6c674)

1. Advanced Parameters : I have changed Advanced Parameters to **Show** but i did not see any changes. what it for?
2. Model folders : It says Model folders. What does it mean Model folders in Local PC or Colab?

**Comment by arenasys** [comment]
Advanced parameters will show [ToMe](https://github.com/dbolya/tomesd) ratio's and some extra settings for Highres. 

The model folder is for local only, the colab notebook determines its own model folder (usually its your google drive under `qDiffusion/models`)
