### ISSUE TITLE
zrok error

### ISSUE THREAD

**Issue by eyetest42** [arenasys/qDiffusion#80]
```
]10;?\[   0.358]   ERROR main.(*enableCommand).run: the zrok service returned an error: [POST /enable][401] enableUnauthorized 
there was a problem enabling your environment!

you are trying to use the zrok service at: https://api.zrok.io/

you can change your zrok service endpoint using this command:

$ zrok config set apiEndpoint <newEndpoint>

(where newEndpoint is something like: https://some.zrok.io/)

PASSWORD: 9uNcqq2t
/tmp/python/lib/python3.10/site-packages/transformers/utils/generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/tmp/python/lib/python3.10/site-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/tmp/python/lib/python3.10/site-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
SERVER: starting
FAILED TO CREATE TUNNEL, LOG:
[ERROR] unable to load environment; did you 'zrok enable'?
```

**Comment by arenasys** [comment]
Using your own zrok token?

**Comment by eyetest42** [comment]
yes

**Comment by arenasys** [comment]
need to go to https://api.zrok.io/ and delete all the environments

**Comment by eyetest42** [comment]
Then what?

**Comment by arenasys** [comment]
error should go away

**Comment by eyetest42** [comment]
It didn't.

**Comment by arenasys** [comment]
unknown zrok problem (`[POST /enable][401] enableUnauthorized`), make an issue with zrok.

**Comment by arenasys** [comment]
Should also be aware that zrok is blocking cross origin requests now, meaning web qdiffusion wont work with zrok.

**Comment by eyetest42** [comment]
That's probably the problem. So how do I use the web version now? My computer can't handle running any SD model or UI on its own.

**Comment by eyetest42** [comment]
I own a Mac, so running qDiffusion locally is not an option.
Colab version is just as broken as the last time I tried it- constant disconnects until eventually it just stops working altogether.

**Comment by arenasys** [comment]
qdiff should be able to run on mac, its just i dont have one. mac has bash, curl and tar, so i think the linux launcher should be similar. added a start-mac.sh. in the qDiffusion folder run, `bash source/start-mac.sh`

**Comment by eyetest42** [comment]
Thanks, I really appreciate that.
I was very glad to see that it actually worked, although very often it would get stuck while generating or fetching generations. Also, accidentally double-clicking 'generate' makes it get stuck too. Not sure why in either case.

**Comment by arenasys** [comment]
Likely due to differences with PyQt on mac. When you say stuck: does it just freeze forever, or only for a while?

**Comment by eyetest42** [comment]
It either stops halfway through generating an image, or when it's trying to fetch/drop the image. Attempting to abort causes the generate button to become unresponsive and I have to reload. Either way, I end up with only a low-resolution preview or no image at all.

Just now (after updating), trying to reload causes it to freeze completely.

I'm on an M2 Mac mini with Sonoma, if that helps.

**Comment by arenasys** [comment]
Think thats connectivity issues? Try switch Operation->Fetching to "Wait"

**Comment by eyetest42** [comment]
Tried it, didn't seem to help much, but it is slightly better than yesterday (I didn't get any finished images).

**Comment by arenasys** [comment]
What's the ping/latency.

**Comment by eyetest42** [comment]
It says about 80-90 ms until it gets stuck. After that hovering over the status doesn't do anything.

**Comment by eyetest42** [comment]
Any advice/progress?
