### ISSUE TITLE
Does qDiffusion support zsnr=True when using Vpred?

### ISSUE THREAD

**Issue by Bionagato** [arenasys/qDiffusion#85]
There is a new model (NoobAI-XL https://civitai.com/models/833294?modelVersionId=962003) that added v-pred for SDXL, and it works really well in qDiffusion. I am wondering if it is possible to load a model with v_prediction mode and zsnr=True in qDiffusion?

**Comment by arenasys** [comment]
v_prediction is available. Afaik zsnr is mostly a training technique and will work fine in qdiffusion.
