### ISSUE TITLE
upscaler download issues

### ISSUE THREAD

**Issue by talon19912** [arenasys/qDiffusion#89]
when ever i try to download an upsacler it doesn't show up in the upscaler folder, ive downloaded several different ones and the don't show up, i'm sure im doing something wrong, i just can't seem to figure it out
![upscaler_proof_1](https://github.com/user-attachments/assets/1110bd18-ada2-45d2-9609-e3f4aa529a60)
![upsacler_proof_2](https://github.com/user-attachments/assets/963e7e9f-1e1a-47fc-90aa-10a703e2ff6c)

**Comment by arenasys** [comment]
upscalers were assumed to be a `.pth`, should be fixed by https://github.com/arenasys/sd-inference-server/commit/ac0064b5736967dc486952859f20f4db35fdd2c3
